name: Get commit and file info
on:
  pull_request:
    types: [opened, synchronized, edited, reopened]
    branches: [ master ]

jobs:
  get_info:
    runs-on: ubuntu-latest
    outputs:
      has_olrs_folder_change: ${{ steps.folder_check.outputs.has_change }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: 'Get a list of changed files to process'
        run: |
          # Fetch enough history for a common merge-base commit
          git fetch origin ${{ github.event.pull_request.head.ref }} --depth $(( ${{ github.event.pull_request.commits }} + 1 ))
          git fetch origin ${{ github.event.pull_request.base.ref }}

          # Show only files from the PR with content filtered by specific git status (Added or Modified):
          git diff-tree --name-only --diff-filter=ACMRT -r \
            --merge-base origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }}
      
      - name: Get changed files
        id: changes
        run: |
          echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo $(git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r HEAD^1 HEAD)
          echo "commits - ${{ github.event.pull_request.commits }}"
         
      - name: Get commit and file info
        id: folder_check
        run: |
          # Get the pull request number
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          TOTAL_FILES_CHANGED=()
          # Get the list of all commits in the pull request
          COMMITS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits")
          
          # Loop through the commits and get the list of files changed in each commit
          for COMMIT_SHA in $(echo "${COMMITS}" | jq -r ".[].sha"); do
            FILES_CHANGED=($(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${COMMIT_SHA}" | jq -r '.files[].filename'))
            TOTAL_FILES_CHANGED=(${TOTAL_FILES_CHANGED[@]} ${FILES_CHANGED[@]})
            echo "for commit: ${COMMIT_SHA}, ${TOTAL_FILES_CHANGED[@]}"
          done
          TOTAL_FILES_CHANGED=($(echo "${TOTAL_FILES_CHANGED[@]}" | tr ' ' '\n' | awk '!a[$0]++' | sort))
          echo "after dedup: ${TOTAL_FILES_CHANGED[@]}"
          has_change=$(echo "${TOTAL_FILES_CHANGED[@]}" | tr ' ' '\n' | grep "docs/[a-z]*.md" | wc -l)
          echo "has_change value: ${has_change}"
          echo "has_change=${has_change}" >> ${GITHUB_OUTPUT}
          
  get_output:
    runs-on: ubuntu-latest
    needs: get_info
    steps:
      - name: check output from get_info
        run: |
          echo "output for has change: ${{ needs.get_info.outputs.has_olrs_folder_change }}"
