name: Deployment Dispatcher

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Select environment"
        options:
        - dev
        - qa
        - qaa

env:
  PROJECT: "k8s"

jobs:
  set-account-id:
    runs-on: ubuntu-latest

    outputs:
      account_id: ${{ steps.determine_account_id.outputs.account_id }}
      folders: ${{ steps.determine_account_id.outputs.folders }}
    steps:
      - name: Set account id
        id: determine_account_id
        run: |
          echo env in set-account-id - ${{ github.event.inputs.environment }}
          if [ "${{ github.event.inputs.environment }}" == "dev" ] || 
             [ "${{ github.event.inputs.environment }}" == "qa" ] ||
             [ "${{ github.event.inputs.environment }}" == "qaa" ]; then
             export ACCOUNT_ID=1234567890
          fi
          echo "account_id=${ACCOUNT_ID}" >> "$GITHUB_OUTPUT"
          echo "folders=(f1 f2 f3)" >> "$GITHUB_OUPUT"
  
  print-output:
    runs-on: ubuntu-latest
    needs: set-account-id
    steps:
      - name: Print output
        run: |
          echo Account ID in set-account-id - ${{ github.event.inputs.environment }}
          echo Account ID from outputs - ${{ needs.set-account-id.outputs.account_id }}
  
  matrix-test:
    runs-on: ubuntu-latest
    needs: set-account-id
    strategy:
      matrix:
        folder: [ join(needs.set-account-id.outputs.folders) ]
    steps:
      - name: Test matrix
        run: |
          echo "Folder: ${{ matrix.folder }}"
    

  trigger-deployment-workflow:
    uses: ./.github/workflows/deploy.yml
    needs: set-account-id
    with:
      account-id: ${{ needs.set-account-id.outputs.account_id }}
