name: Deployment > Workflow > Automated Runner

on:
  workflow_call:
    inputs:
      account-id:
        required: true
        type: string
      region:
        type: string
        default: 'us-east-1'

env:
  INPUT_ACCOUNT_ID: ${{ inputs.account-id }}
          
jobs:
  deployment_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow input
        run: |
          echo "account-id - ${INPUT_ACCOUNT_ID} - ${{ inputs.account-id }}"
      - name: Get changed files
        run: |
          files=$(git ls-files --modified)
          has_change=$(echo "${files}" | grep ".github/[a-z]*flows" | wc -l)
          echo "has_change: ${has_change}"
        
