name: Deployment Workflow Automated Runner

on:
  workflow_call:
    inputs:
      account-id:
        required: true
        type: string
      region:
        type: string
        default: 'us-east-1'
    
jobs:
  deployment_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow input
        run: |
          echo "account-id - ${INPUT_ACCOUNT_ID}"
        env:
          INPUT_ACCOUNT_ID: ${{ inputs.account-id }}
