name: Fetch PR body

on:
  pull_request:
    types: [opened]

jobs:
  pr_created:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get PR body
        run: |
          body="${{ github.event.pull_request.body }}"
          echo "$body"